- name: Determine whether roundcube is configured
  stat: path=/var/www/roundcube/config.inc.php
  register: roundcube_config

- name: Install roundcube dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php5.6
    - php5.6-sqlite3
    - php5.6-mcrypt
    - php5.6-gd
    - php5.6-pspell
    - php5.6-intl
    - php5.6-curl
    - aspell
    - aspell-en
    - php5.6-xml
    - php5.6-mbstring
    - php5.6-pgsql
    - php5.6-zip
  tags:
    - dependencies

- name: Clone roundcube
  git: repo=https://github.com/roundcube/roundcubemail.git
       dest=/var/www/roundcube
       version={{ webmail_version }}
       update=no
       accept_hostkey=yes

- name: Get Composer installer
  get_url: url=https://getcomposer.org/installer
           dest=/tmp/composer-installer

- name: Copy composer configuration
  copy: src=var_www_roundcube_composer.json dest=/var/www/roundcube/composer.json
    owner=root
    group=www-data
    mode=0644

- name: Install Composer
  command: php /tmp/composer-installer
           chdir=/root
           creates=/root/composer.phar

- name: Initialize composer
  command: php /root/composer.phar install --no-dev
           chdir=/var/www/roundcube
           creates=/var/www/roundcube/vendor/autoload.php
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Remove installer directory
  file: path=/var/www/roundcube/installer state=absent

- name: Install Roundcube configuration
  template: src=var_www_roundcube_config_config.inc.j2 dest=/var/www/roundcube/config/config.inc.php

- name: Set permissions for roundcube
  file: path=/decrypted/roundcube owner=vmail group=www-data mode=0775 state=directory recurse=true

- name: Make logs and temp directories writable by web server
  file: path=/var/www/roundcube/{{ item }} mode=0775 state=directory
  with_items:
    - temp
    - logs

- name: Make roundcube directory accessible to web server
  file: path=/var/www/roundcube group=www-data recurse=yes state=directory

- name: Install sieve plugin configuration
  copy: src=var_www_roundcube_plugins_managesieve_config.inc.php
    dest=/var/www/roundcube/plugins/managesieve/config.inc.php
    owner=root
    group=www-data
    mode=0644

- name: Install global sieve
  copy: src=var_www_roundcube_config_global.sieve
    dest=/var/www/roundcube/config/global.sieve
    owner=root
    group=www-data
    mode=0644

- name: Install carddav plugin configuration
  copy: src=var_www_roundcube_plugins_carddav_config.inc.php
    dest=/var/www/roundcube/plugins/carddav/config.inc.php
    owner=root
    group=www-data
    mode=0644

- name: Install Google 2-factor authentication plugin configuration
  copy: src=var_www_roundcube_plugins_twofactor_gauthenticator_config.inc.php
    dest=/var/www/roundcube/plugins/twofactor_gauthenticator/config.inc.php
    owner=root
    group=www-data
    mode=0644

- name: Configure Apache for Roundcube
  template: src=etc_apache2_sites-available_roundcube.j2
    dest=/etc/apache2/sites-available/roundcube.conf
    group=root owner=root force=yes

- name: Enable Roundcube site
  command: a2ensite roundcube.conf creates=/etc/apache2/sites-enabled/roundcube.conf
  notify: restart apache

- name: Create symlink for php and apache2
  file: src=/etc/apache2/mods-available/php5.6.conf  dest=/etc/apache2/mods-enabled/php5.6.conf
  state: link

- name: Create symlink for php and apache2
  file: src=/etc/apache2/mods-available/php5.6.load  dest=/etc/apache2/mods-enabled/php5.6.load
  state: link
